2022-09-05 15:35:33,279 ERROR: Exception on /translate [POST] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/routes.py", line 203, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'jsonify' is not defined
2022-09-05 15:36:34,918 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:36:50,430 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:36:55,062 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:37:01,808 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 15:37:08,033 ERROR: Exception on /translate [POST] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/routes.py", line 203, in translate_text
    return jsonify({'text': translate(request.form['text'],
NameError: name 'translate' is not defined
2022-09-05 15:37:36,285 INFO: Microblog startup [in /src/app/__init__.py:59
2022-09-05 21:53:43,066 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 21:54:29,582 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 21:55:23,934 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 21:57:18,878 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 21:58:40,129 ERROR: Exception on /explore [GET] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/main/routes.py", line 53, in explore
    next_url = url_for('explore', page=posts.next_num) \
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/usr/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore' with values ['page']. Did you mean 'main.explore' instead?
2022-09-05 21:59:31,790 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 21:59:41,005 ERROR: Exception on /explore [GET] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/main/routes.py", line 55, in explore
    prev_url = url_for('explore', page=posts.prev_num) \
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python3.10/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/usr/lib/python3.10/site-packages/werkzeug/routing.py", line 2315, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore' with values ['page']. Did you mean 'main.explore' instead?
2022-09-05 21:59:56,078 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 22:00:11,839 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 22:02:28,442 ERROR: Exception on /auth/reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MSwiZXhwIjoxNjYyNDE1OTE3Ljc1MjQ4MTV9._gYl_BgURRDwfQDGQvLnADKnE8c8yGzO1EXoRZtjo10 [GET] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/src/app/auth/routes.py", line 75, in reset_password
    return render_template('reset_password.html', form=form)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password.html
2022-09-05 22:03:55,198 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 22:06:00,740 INFO: Microblog startup [in /src/app/__init__.py:78
2022-09-05 22:30:49,884 INFO: Microblog startup [in /src/app/__init__.py:76
2022-09-05 22:30:59,959 INFO: Microblog startup [in /src/app/__init__.py:76
2022-09-05 23:11:20,330 INFO: Microblog startup [in /src/app/__init__.py:76
2022-09-06 00:12:10,540 INFO: Microblog startup [in /src/app/__init__.py:76
2022-09-06 02:07:09,030 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:17:39,629 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:33:13,514 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:39:31,847 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:39:54,566 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:40:22,866 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:42:54,394 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:43:05,968 INFO: Microblog startup [in /src/app/__init__.py:80
