2022-09-06 02:43:12,760 ERROR: Exception on /index [GET] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/main/routes.py", line 44, in index
    return render_template('index.html', title=_('Microblog Home'),
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/src/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/src/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/src/app/templates/base.html", line 58, in block 'navbar'
    action="{{ url_form('main.search') }}">
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'url_form' is undefined
2022-09-06 02:43:39,786 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:46:00,618 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:46:09,012 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:47:20,532 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:47:22,500 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:48:15,309 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:48:24,582 ERROR: Exception on /search [GET] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/main/routes.py", line 158, in search
    return render_template('search.html', title=_('Search'), posts=posts,
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/src/app/templates/search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/src/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/src/app/templates/base.html", line 95, in block 'content'
    {% block app_content %}{% endblock %}
  File "/src/app/templates/search.html", line 8, in block 'app_content'
    {% if len(posts) == 0 %}
  File "/usr/lib/python3.10/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'len' is undefined
2022-09-06 02:48:44,032 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:50:14,289 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:51:10,457 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:51:35,492 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:53:54,896 ERROR: Exception on /index [POST] [in /usr/lib/python3.10/site-packages/flask/app.py:1455
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/src/app/main/routes.py", line 34, in index
    db.session.commit()
  File "<string>", line 2, in commit
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1435, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 839, in commit
    self.session.dispatch.after_commit(self.session)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/src/app/models.py", line 34, in after_commit
    if isintance(obj, SearchableMixin):
NameError: name 'isintance' is not defined
2022-09-06 02:54:23,723 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:54:36,921 INFO: Microblog startup [in /src/app/__init__.py:80
2022-09-06 02:55:11,397 INFO: Microblog startup [in /src/app/__init__.py:80
